version: '3.8'

services:
  chorusv1:
    image: local/chorusv1-stage4
    container_name: chorusv1
    privileged: true
    entrypoint: /root/stage5-files/install.sh
    ports:
      - "8888:80"
      - "8080:8080"
      - "9001:9001"
    volumes:
      - ./stage5-files:/root/stage5-files
      - ./${pwd}/var-lib-docker:/var/lib/docker
    environment:
      NEXTCLOUD_VIRTUAL_HOST: ${NEXTCLOUD_VIRTUAL_HOST:hip.local}
      IAM_BASE_URL: http://keycloak.local:8080
      KEYCLOAK_HOSTNAME_URL: http://keycloak.local:8080


