version: '3.8'

services:
  chorusv1:
    image: registry.build.chorus-tre.ch/chorusv1-stage4
    container_name: chorusv1
    privileged: true
    entrypoint: /root/stage5-files/install.sh
    ports:
      - "8888:80"
      - "8080:8080"
      - "9001:9001"
    volumes:
      - ./stage5-files:/root/stage5-files
      - ./${pwd}/var-lib-docker:/var/lib/docker
      # - ./data/mnt:/mnt
      # - ./data/db_keycloak:/root/frontend/keycloak/postgres_data
      # - ./data/db_nextcloud:/root/frontend/nextcloud-docker/db
      # - ./data/redis_nextcloud:/root/frontend/nextcloud-docker/redis/data
      # - ./data/redis_gateway:/root/frontend/gateway/redis/data
    environment:
      NEXTCLOUD_VIRTUAL_HOST: ${NEXTCLOUD_VIRTUAL_HOST:-hip.local}
      IAM_BASE_EXTERNAL_URL: http://keycloak.local:8080
      KEYCLOAK_HOSTNAME_URL: http://keycloak.local:8080
      REMOTE_APP_API: http://hip.local:9001/api
      COLLAB_REMOTE_APP_API: http://hip.local:9001/api


