services:
  chorusv1:
    image: registry.build.chorus-tre.ch/chorusv1
    container_name: chorusv1
    privileged: true
    entrypoint: /root/run-files/run.sh
    ports:
      - "8888:80"
      - "8080:8080"
      - "9001:9001"
    volumes:
      - ./run-files:/root/run-files
      - ./${pwd}/var-lib-docker:/var/lib/docker
      - ./data/mnt:/mnt
      - ./data/db_keycloak:/root/frontend/keycloak/postgres_data
      - ./data/db_nextcloud:/root/frontend/nextcloud-docker/db
      - ./data/redis_nextcloud:/root/frontend/nextcloud-docker/redis/data
      - ./data/redis_gateway:/root/frontend/gateway/redis/data
    environment:
      # landing url 
      BASE_URL: http://localhost:8888
      # allowed base domain
      NEXTCLOUD_VIRTUAL_HOST: ${NEXTCLOUD_VIRTUAL_HOST:-hip.local}
      # keycloak url
      IAM_BASE_EXTERNAL_URL: http://keycloak.local:8080
      KEYCLOAK_HOSTNAME_URL: http://keycloak.local:8080
      # xpra urls
      REMOTE_APP_API: http://hip.local:9001/api
      COLLAB_REMOTE_APP_API: http://hip.local:9001/api
      BACKEND_DOMAIN: http://hip.local:9001
      ALLOWED_FRAME_DOMAIN: hip.local:9001
      # background colors
      BACKGROUND_COLOR: "#07020f"


